# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Tùng Bach Lý
title: Nonprofit Leader | Operational Excellence through Strategic Tech
email: mail@tung.ly
# website: tungly.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  tungly
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: tungly
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Get Time
  icon: fas fa-calendar-plus
  url: https://calendar.app.google/wED2LWs7nkTEycJU6
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-3QP4H3BRV2"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am passionate about using data and technology to enable social justice and community development. I work with diverse teams and partners to deliver value-added services, evaluate program outcomes, and inform strategic decisions. I lead the optimization and implementation of new technologies and processes to support civil and social impact programs and operations. I have over 18 years of experience in data engineering, web management, and digital marketing, with certifications in information management and data science. I leverage my engineering background to bring a scientific and creative approach to problem solving and innovation.

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Professional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 4.0 Schools
        link: 4pt0.org
        # link_text: boringcompany.com
        sub_title: Managing Director of Operations
        caption: January 2023 - June 2024
        quote: >
          Assist leading the operations function of a non-profit venture philanthropy with a $6 million annual budget.
        description: | # this will include new lines to allow paragraphs
          Facilitate development of organization's theory of change and program logic models with executive leadership.
          Cooperatively train staff and provide accountability systems to ensure the organization adheres to its mission via execution of logic models and theory of change.
          Lead cross functional teams and external partners to produce third party program evaluation and research reports.
          Consult with individual program sub functions to set, evidence, and collect data for key performance indicators.
          Drive data collection projects with customer journey mapping to ensure a human-centered approach leads the fellow and alumni experience.
          Consult with program directors and finance function to translate functional requirements of receiving and granting funds to user stories and technical specifications.
          Lead technical direction for the organization by serving as Recommender and Approver in the organization's RAPID decision rights model for all data governance and data systems.
          Review projects for technical feasibility and adherence to mission as Consultant or Approver in organization's MOCHA project management method.
          Represent the organization for professional development content, alumni programming, and partnership committees on data strategy and information technology for early stage entrepreneurship and fellowship application and selection.
          Produced user-centered data collection instruments in Qualtrics and leveraged Postgres SQL, Microsoft Excel, and Google Sheets to extract, load, and transform data for visualization. Customer journey mapping conducted on Google Sheets. Collaborated cross functionally on Slack, using Microsoft Word, Google Docs, Google Slides, and Zoom. Administered Google Workspace, Slack, and Zoom. Supported all aspects of maintaining MacBook Pros as organization provided virtual workspace terminals.
      - layout: left
        title: 4.0 Schools
        link: 4pt0.org
        sub_title: Data Engineer
        caption: January 2021 - January 2023
        quote: >
          4.0 invests in new, community-centered models of education, and provides coaching, curriculum, community and cash to those with the imagination to create a more equitable education ecosystem.
        description: |
            Joins 4.0 Schools in its Fund III chapter of growth where it levels up from startup and scale modes to operational maturity. The Data Engineer role:
            * Built 4.0's capacity to leverage data systems to make their work more accurate, equitable, and simple.
            * Implemented a first ever fellowship and alumni portal, streamlining how the 4.0 community interacts with one another
            * Ensured all fellowship-candidates, fellows, alumni, and staff easily use the portal
      - layout: left
        title: City of New Orleans
        link: nola.gov
        sub_title: Web Manager
        caption: January 2016 - January 2021
        quote: >
          The Office of Information Technology and Innovation facilitates effective, cost efficient use of technology by spearheading the assessment and deployment of technology based business management solutions, and service delivery strategies.
        description: |
            A second tour of duty on the mission to enable municipal government to develop digital products and services. Current objectives non-exclusively include:
            * Maintain a modern web environment and suite of digital marketing services
            * Make it simple for citizens to find information
            * Deliver value added service via digital marketing services platform with training & design thinking
            * Increase the success rate of innovation by knowing our audiences, customers, and residents
      - layout: left
        title: PosiGen Solar Engergy and Energy Efficiency
        link: posigen.com
        sub_title: Manager of Innovation & Technology
        caption: August 2014 - January 2016
        quote: >
          Dedicated to increasing energy independence and ensuring the financial security of the communities we serve, PosiGen pairs energy efficiency retrofits and solar power systems to reduce household energy consumption.
        description: |
          PosiGen's mission of making a positive financial impact on the lives of homeowners resonated with me. I was recruited to the solar startup for his proven track record of marshaling tech-reluctant managers and staff in enterprise system implementations and integrations. I managed PosiGen's technology supporting the sales process including but not limited to:
          * GIS analysis of markets including producing maps and data for business development
          * housing burden and weather mitigation cost research supporting governmental relations
          * marketing automation and lead generation
          * telemarketing and lead qualifying
          * sales presentation and customer savings modeling
          * sales automation and electronic contracting
          * consumer information compliance and customer identity security
          
          I directly drove down the cost to acquire customers while increasing customer data quality for the enablement of lower maintenance costs over time.
      - layout: left
        title: City of New Orleans
        link: nola.gov
        sub_title: User Adoption Specialist
        caption: July 2011 - August 2014
        quote: >
          The Office of Information Technology and Innovation facilitates effective, cost efficient use of technology by spearheading the assessment and deployment of technology based business management solutions, and service delivery strategies.
        description: |
            Mayor Mitch Landrieu emphasized leveraging data for decision making. A critical lack of data existed from the missed ownership opportunities resulting from previous administrations' preference toward outsourcing IT. I was recruited for my strong bridge building capacity, which was much needed to establish legitimacy to the department whose history was plagued by corruption. Although simplicity intuitively promotes use and ownership, I focused on coherence and understanding. With intricate complexities involved in the service, compliance, governing, policy, and protection processes of the City of New Orleans I set out not to simplify processes for staff but to create coherence among systems and endorse greater understanding between people and the systems they use.
            I focused on enterprise systems that would be leveraged to improve customer service and increase revenue through economic development, including but not limited to permitting and licensing, land use and code enforcement, IT service delivery, and interdepartmental collaboration platforms.
            Projects Included:
            * BlightSTATUS.nola.gov blighted property search resource
            * OneStop Online Licensing and Permitting
            * NoticeMe.nola.gov proposed land-use change notification tool
            * Rapid, Crowdsourced, Property Condition Data Techarrette
      - layout: left
        title: Louisiana Public Health Institute
        link: lphi.org
        sub_title: Senior Program Analyst
        caption: August 2005 - July 2011
        quote: >
          LPHI creates and fosters collaborative endeavors in the areas of health information, public policy, applied research, and community capacity enhancement.
        description: |
            I joined LPHI Wednesday August 24th 2005, days before Hurricane Katrina made landfall. The next couple months involved standing up a temporary office infrastructure 100 miles west in Baton Rouge, kludging and salvaging weathered and neglected equipment for reestablishing a headquarters in New Orleans, and extending infrastructure support to partner organizations including the Partnership for Access to Healthcare.
            As operations recovered, I took on new technology projects. I was instrumental in developing an automated information extraction system for paper survey forms used to rapidly conduct surveys across 18 of the most severely hurricane-affected parishes in Louisiana. I began to facilitate the end to end implementation of technology from facilitating system selection to installing infrastructure to configuring the EMR to supporting physician adoption of the system through a “train the trainer” model.
            Greater resources were made available as LPHI's track record was proven. I tackled business process re-engineering to enable the business intelligence and reporting requirements of federal grants. A team was hired to handle standing up new clinics. I coached and led this team of implementers who handled everything from EMR selection to achieving meaningful use to connecting to the health information exchange.
            Projects Included:
            * Health and Population Estimate
            * Partnership for Access to Healthcare Information Systems
            * Primary Care Access and Stabilization Grant
            * Louisiana Health Care Information Technology Resource Center
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Tulane University
        caption: 2000 - 2005
        sub_title: Biomedical Enginering, Political Science

  - title: Certifications And Professional Organizations
    layout: list
    content:
      - layout: top-middle
        title: Applied Data Science I Scientific Computing & Python
        caption: 2021
        link: WWW.CREDLY.COM/BADGES/7A006636-29DE-4AA4-BAEE-A9F3A62AFF1E
      - layout: top-middle
        title: Nancy M. Marsiglia Institute Of Justice
        caption: 2018
      - layout: top-middle
        title: Norman C. Francis Leadership Institute
        caption: 2017
      - layout: top-middle
        title: Certified Information Professional
        sub_title: AIIM, License 97512
        caption: 2013 - 2016
      - layout: top-middle
        title: Loyola Institute Of Politics
        caption: 2013
      - layout: top-middle
        title: New Orleans Regional Leadership Institute
        caption: 2012

  - title: Volunteer Experience
    layout: list
    content:
      - layout: left
        title: VAYLA New Orleans
        caption: 2008 - Present
        quote: >
          A progressive multi-racial community-based organization in New Orleans that empowers youth and families through supportive services and organizing for cultural enrichment and positive social change.
        description: |
            * Chairman, Board of Directors -- 2012 - Present
            * Secretary, Board of Directors -- 2009
            * Member, Board of Directors -- 2008

      - layout: left
        title: Arts Council New Orleans
        caption: 2018 - 2024
        quote: >
          Expand opportunities for diverse artistic expression and bring the community together in celebration of our rich multi-cultural heritage.
        description: |
            * LUNA Fête committee -- 2018 - 2022

      - layout: left
        title: Crescent City Community Land Trust
        caption: 2018 - 2022
        quote: >
          Increasing opportunity and equity in New Orleans through community land trust-based commercial and residential development, helping local families access jobs, grow their own businesses, and live in affordable housing near areas of significant economic development and opportunity.
        description: |
            * Vice President, Board of Directors -- 2021 - 2022
            * Secretary, Board of Directors -- 2019 - 2020

      - layout: left
        title: First Grace United Methodist Church
        caption: 2019 - 2022
        quote: >
          Where the city worships | All are welcome
        description: |
            * Vice Chair, Church Council -- 2020 - 2022

      - layout: left
        title: Mid-City Security District
        caption: 2018 - 2021
        quote: >
          A political subdivision of the State of Louisiana to provide security in Mid-City above and beyond that which would normally be provided by the New Orleans Police Department.

      - layout: left
        title: White House Police Data Initiative
        caption: 2015
        description: |
          *  Member of volunteer Elite Tech Team supporting Camden County Police Department at initiative launch

      - layout: left
        title: Travel + Social Good New Orleans
        caption: 2015 - 2017
        quote: >
          Now known as Impact Travel Alliance. Transforming the travel industry to act as a catalyst for solving the world's most pressing issues.

      - layout: left
        title: Awesome Foundation, New Orleans Chapter
        caption: 2013 - 2016
        quote: >
          No strings attached, monthly micro-granting group

      - layout: left
        title: Social Entrepreneurs Of New Orleans
        caption: 2008 - 2011
        quote: >
          Now known as Propeller: A Force for Social Innovation
        description: |
            * Infrastructure Committee Chair -- 2009 - 2011

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
