# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Tùng Bach Lý
title: Nonprofit Leader | Operational Excellence through Strategic Tech
email: mail@tung.ly
# website: tungly.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  tungly
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: tungly
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Get Time
  icon: fas fa-calendar-plus
  url: https://calendar.app.google/wED2LWs7nkTEycJU6
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-3QP4H3BRV2"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am passionate about using data and technology to enable social justice and community development. I work with diverse teams and partners to deliver value-added services, evaluate program outcomes, and inform strategic decisions. I lead the optimization and implementation of new technologies and processes to support civil and social impact programs and operations. I have over 18 years of experience in data engineering, web management, and digital marketing, with certifications in information management and data science. I leverage my engineering background to bring a scientific and creative approach to problem solving and innovation.

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Professional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 4.0 Schools
        link: 4pt0.org
        # link_text: boringcompany.com
        sub_title: Managing Director of Operations
        caption: January 2023 - June 2024
        quote: >
          4.0 invests in new, community-centered models of education, and provides coaching, curriculum, community and cash to those with the imagination to create a more equitable education ecosystem.
        description: | # this will include new lines to allow paragraphs
            In closing 4.0's Fund III chapter of growth, I shifted my role to incorporate a broader approach to operational maturity by:
            * Leading Evaluation, Learning and Data initiatives including defining a new Theory of Change, developing Logic Models, managing data collection and reporting, and directing program evaluation.
            * Developing and leading knowledge management implementations and organizational learning initiatives
            * Maintain an effective and safe remote work environment
      - layout: left
        title:
        link:
        sub_title:
        caption:
        quote: >
          4.0 invests in new, community-centered models of education, and provides coaching, curriculum, community and cash to those with the imagination to create a more equitable education ecosystem.
        description: |
            Joins 4.0 Schools in its Fund III chapter of growth where it levels up from startup and scale modes to operational maturity. The Data Engineer role:
            * Built 4.0's capacity to leverage data systems to make their work more accurate, equitable, and simple.
            * Implemented a first ever fellowship and alumni portal, streamlining how the 4.0 community interacts with one another
            * Ensured all fellowship-candidates, fellows, alumni, and staff easily use the portal
      - layout: left
        title: City of New Orleans
        link:
        sub_title:
        caption:
        quote: >

        description: |

      - layout: left
        title: PosiGen Solar Engergy and Energy Efficiency
        link:
        sub_title:
        caption:
        quote: >

        description: |

      - layout: left
        title: City of New Orleans
        link:
        sub_title:
        caption:
        quote: >

        description: |

      - layout: left
        title: Louisiana Public Health Institute
        link:
        sub_title:
        caption:
        quote: >

        description: |

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Tulane University
        caption: 2000 - 2005
        sub_title: Biomedical Enginering, Political Science

  - title: Certifications And Professional Organizations
    layout: list
    content:
      - layout: top-middle
        title: Applied Data Science I Scientific Computing & Python
        caption: 2021
        link: WWW.CREDLY.COM/BADGES/7A006636-29DE-4AA4-BAEE-A9F3A62AFF1E
      - layout: top-middle
        title: Nancy M. Marsiglia Institute Of Justice
        caption: 2018
      - layout: top-middle
        title: Norman C. Francis Leadership Institute
        caption: 2017
      - layout: top-middle
        title: Certified Information Professional
        sub_title: AIIM, License 97512
        caption: 2013 - 2016
      - layout: top-middle
        title: Loyola Institute Of Politics
        caption: 2013
      - layout: top-middle
        title: New Orleans Regional Leadership Institute
        caption: 2012


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
